import pandas as p

scores = p.read_csv("data.csv")
print(scores)
print(scores.max())
print(scores.shape)
print(scores.count())
print(scores.mean())
print(scores.min())
print(scores.sum())
print(scores.median())
print(scores['Student id'])
print(scores['Student id'].max())
print(scores['Student id'].min())
print(scores.head())
print(scores.tail())
print(scores.dtypes)
print(scores['Student id'],type(scores['Student id']))
print(scores[scores['Student id'] == 1001])
